version: "3"

services:
    kafka:
        hostname: kafka
        container_name: kafka
        build:
            context: .
            dockerfile: Dockerfile-kfk
        ports:
            - "9092:9092"