version: "3"

services:
    kafka:
        hostname: kafka
        container_name: kafka
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9092:9092"
    app:
        hostname: app
        container_name: app
        build:
            context: .
            dockerfile: go/Dockerfile
        depends_on:
            - kafka